### ISSUE TITLE
Snapshot recording seems to be saving duplicate snapshots with different IDs

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-media#143]
Example:

https://dash.evercam.io/v1/cameras/creedon-millst2/recordings/snapshots/2015-11-17T17:58:46.000Z

Scroll +1 -1 to see.

@shankardevy  I guess this is for you

@mosic  ...you might have an opinion about this.

**Comment by shankardevy** [comment]
@marcoherbst I don't see an issue here. that particular camera is recording per sec and what I assume (pretty much sure) is that a request that got sent to the camera on 46th second was queued and then there was request sent at 47th second and both of them got responded at the same time  and hence bearing the same timestamp in the image. However, since we sent the request on two distinct timestamps, we store the same in the database as two separate entries. On the media end, we can't identify if the camera responds the same image for two consecutive requests. I would close this unless you want to handle this in any other way.

**Comment by ijunaidfarooq** [comment]
I am closing this issue for now. But everyone in @DevTeam should keep an eye on this in case, This occurs again, You are allowed to re-open it again.
@evercam/write-access-all-repos
