### ISSUE TITLE
Give a better response code for broken images

### ISSUE THREAD

**Issue by azharmalik3** [evercam/evercam-media#194]
@mosic API gave image in response "Your recorded images are save" which is causing bad timelapse stream. 

I just want to know have you fixed this issue or not? If not, could we have that?

**Comment by mosic** [comment]
@azharmalik3 The response for missing snapshots from `evercam-media` is 404 and was like that since the original implementation of the snapshot endpoint.

What you're referring to comes from the `evercam-api`. The issue was raised in the email on 29. March and I changed the snapshot response to return 203 status code on the 30. March and responded to the original email. As I mentioned there, I know that 203 is the wrong code but changing it to be an error code would require changing dashboard code, which I wanted to avoid since this is an one-off hack which we will remove soon(ish).

You can add a check to use only snapshots returned with 200 code in timelapses.

**Comment by marcoherbst** [comment]
Thanks @mosic  , we both knew it had been discussed, but had forgotten the outcome. That's perfect. M
