### ISSUE TITLE
Collection of items to discuss with Milos

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-media#220]
+ Validation of parameters is a lot more work in Elixir than in Ruby
+ Currently media endpoints do not have robust error handling (e.g. for wrong parameters).

**Comment by mosic** [comment]
* I'd argue that it's the other way around, there is a lot of work either way. Here is an example of validating input for camera creation in Ruby: [evercam-api/camera_create.rb](https://github.com/evercam/evercam-api/blob/adaf52641126b50befc1206b27e6a233ec7b83ee/lib/actors/camera_create.rb)
* They do have error handling, you were probably thinking about parameter validation. The newly added is the only endpoint where that is the case, and that's only because it was made in ~30 minutes. As Junaid's pull request showed, it's pretty easy to cover most or all cases it can fail with.
