### ISSUE TITLE
Test snapshot fails, but live view works ...

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-media#252]
https://dash.evercam.io/v1/cameras/valgeo

This is an example of a Foscam style camera (this one is Geovision) where the auth must be in the URL.

**Comment by mosic** [comment]
I think I know what is the issue here, I'll take care of it.

**Comment by mosic** [comment]
Fixed in https://github.com/evercam/evercam-dashboard/commit/f95fabc83daa2c72399e935e5751fd21c750b5da.

The problem was that `?` and `&` were replaced with strings in the dashboard, which should then be switched back in the api. This was introduced in 2014 (https://github.com/evercam/evercam-api/commit/3e66fb1896ac490204138a515879e37b29b58758), I'm guessing it was because evercam-api didn't handle special characters in parameters very well.

This problem doesn't exist in media, so I just had to remove substitution in the dashboard.
