### ISSUE TITLE
Last login required in PATCH endpoint

### ISSUE THREAD

**Issue by Zulqarnain-Mustafa** [evercam/evercam-media#298]

**Comment by ijunaidfarooq** [comment]
@Zulqarnain-Mustafa it's not a bug.. its enhancement!

**Comment by mosic** [comment]
@Zulqarnain-Mustafa Can you elaborate? We have 5 `PATCH` endpoints right now. Which one has a bug? What's the bug? Is the login required and not needed or the other way around?

**Comment by ijunaidfarooq** [comment]
@mosic He accidentally appointed it as a bug.

The issue was: we are doing a `last_login_at` for a user when user sign in. So As Android and iOS using API so there is no way to update it for both the applications. That's what he asking for.

But in this case we also need to add this to Sign up process that when User just created its last login should be set to its current time..
