### ISSUE TITLE
Message is not user friendly for test snapshot

### ISSUE THREAD

**Issue by Zulqarnain-Mustafa** [evercam/evercam-media#299]
https://media.evercam.io/v1/cameras/test

message = "Camera url is not found.";

**Comment by Zulqarnain-Mustafa** [comment]
Here is scenario in which i am testing the application:
IP : 176.126.42.134
HTTP Port: 8083
RTSP Port: 554

Port is open but i pass the wrong the snapshot URL, so the current message in this scenario is not suitable. The previous message was `"The port is open but we can't seem to connect. Check that the camera model and credentials are correct."`
My suggestion is, as the only Snapurl is wrong, so the message should be like "The port is open but we can't seem to connect. Please check your snapshot url."

**Comment by marcoherbst** [comment]
Excellent. 
Something to be aware of .... in the example you provided, it has defaulted to rtsp 554 ... which probably is not correct. In this case (rtsp closed) we would NOT want to add this port by default. It should be necessary for the user to actually type in 554 (or something else). 

The reason is that otherwise the live view will always try to load the rtsp stream. If there is no rtsp value then it will load faster by going straight to http. 

This isn't relevant to this ticket, but @Zulqarnain-Mustafa  , i just wanted you to get this info.

**Comment by azharmalik3** [comment]
@Zulqarnain-Mustafa Failed to replicate this message.

**Comment by azharmalik3** [comment]
Done.
