### ISSUE TITLE
POST /cameras/{id}/ptz/presets/create/{preset_name} error

### ISSUE THREAD

**Issue by affan00** [evercam/evercam-media#397]
This endpoint has a bug in it.Preset name should not be passed with the URL because when a preset name with space is passed with it, the URL breaks and an error message is displayed.

Fix this

**Comment by ijunaid8088** [comment]
In current situation evercam-media endpoint was getting the preset_name in url.. thats why It wasnt being accepted with spaces..

Now: I have made few changes to create presets with common names instead of with dash.. which was the previous case..

during that changes there was one other endpoint which was effecting the change

`post "/cameras/:id/ptz/presets/:preset_token", ONVIFPTZController, :setpreset` 

was the above one.. When I was passing preset_name as post parameter to create preset endpoint
`post "/cameras/:id/ptz/presets/create", ONVIFPTZController, :createpreset`

Instead of going to create it was going to set preset.. and was taking `create` as `preset_token` in set preset endpoint.. 

So i made a change in this endpoint as well so now it is 
`post "/cameras/:id/ptz/presets/:preset_token/set", ONVIFPTZController, :setpreset`

I have confirmed from @Zulqarnain-Mustafa that  set preset endpoint is not being used in Apps so no changes are required in apps and same for dashboard.. In case any one see any possiblity that.. This change will create problem to any application then do point..

**Comment by ijunaid8088** [comment]
Done on media and dashboard both sides!
