### ISSUE TITLE
DB Queries ... let's optimise

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-media#482]
https://postgres.heroku.com/databases/evercam-api-heroku-postgresql-cobalt#metrics

Cobalt = Camera Activities > 2 very slow queiries here. Not critical.
Rose = Cameras > 3 queries 0.5 to 1 sec ... a big opportunity here to improve. Important.

**Comment by azharmalik3** [comment]
Looked into Heroku DB matrices and notice that `camera_activities` and `vendor_model` queries take some extra time due to double queries. One query to get total records count and then the second query to get paginated data. So, removed these duplicate queries and used one query to get count and data.
